accounts/urls.py
from django.conf.urls import url
from accounts.views import AdminLoginView, LogoutView

urlpatterns = [
    url(r'^$', AdminLoginView.as_view(), name='adminlogin'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),

]

art_profile/urls.py
from django.conf.urls import url
from art_profile.views import SuccessView, PublishView, AllproductView, SingleproductView

urlpatterns = [
    url(r'^add-detail/', SuccessView.as_view(), name='add'),
    url(r'^publish/', PublishView.as_view(), name='publish'),
    url(r'^all_products/', AllproductView.as_view(), name='all_products'),
    url(r'^(?P<productlist_slug>[\w-]+)/', SingleproductView.as_view(), name='singleproduct'),


]

printed_vilage/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from art_profile.views import HomeView
from printed_vilage import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^profile/', include('art_profile.urls', namespace='art_profile')),
    url(r'^myprofile/', include('myprofile.urls', namespace='myprofile')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

art_profile/models.py
from __future__ import unicode_literals

from django.db import models
from django.conf import settings
from django.utils.crypto import get_random_string
from django.utils.text import slugify
# Create your models here.

class Category(models.Model):
    categorys = models.CharField(max_length=50, null=True, blank=True)

    def __str__(self):  # __unicode__ on Python 2
        return self.categorys


class SubCategory(models.Model):
    tag = models.CharField(max_length=450, null=True, blank=True)
    category = models.ForeignKey(Category, related_name='tag_category', null=True, blank=True)

    def __str__(self):  # __unicode__ on Python 2
        return self.tag
class Maincategory(models.Model):
    main_categorys = models.CharField(max_length=100, null=True, blank=True)

    def __str__(self):  # __unicode__ on Python 2
        return self.main_categorys

class Productstyle(models.Model):
    product_styles = models.CharField(max_length=250, null=True, blank=True)

    def __str__(self):  # __unicode__ on Python 2
        return self.product_styles

class Productsize(models.Model):
    product_sizes = models.CharField(max_length=250, null=True, blank=True)
    product_style = models.ForeignKey(Productstyle, related_name='productstyle', null=True, blank=True)

    def __str__(self):  # __unicode__ on Python 2
        return self.product_sizes



class Login_info_table(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='art_detail')
    title = models.CharField(max_length=100, null=True, blank=True)
    image_filename = models.ImageField(upload_to='arts_upload')
    main_category = models.ForeignKey(Maincategory, related_name='main_category', null=True, blank=True)
    category = models.ForeignKey(Category, related_name='art_category', null=True, blank=True)
    product_style = models.ForeignKey(Productstyle, related_name='product_style', null=True, blank=True)
    tags = models.ManyToManyField(SubCategory, related_name='art_tags')
    product_size = models.ForeignKey(Productsize, related_name='product_size', null=True, blank=True)
    like_count = models.IntegerField(default=0)
    dislike_count = models.IntegerField(default=0)
    Price = models.IntegerField(default=1)
    designer = models.CharField(max_length=100, null=True, blank=True)
    description = models.CharField(max_length=250, null=True, blank=True)
    content_adult_type = models.BooleanField(default=False)
    copyright = models.BooleanField(default=False)
    status = models.CharField(default="Draft", null=True,blank=True,max_length=50)
    slug = models.SlugField(max_length=255, unique=True, auto_created=True, editable=False)

    def save(self, *args, **kwargs):
        super(Login_info_table, self).save(*args, **kwargs)
        if not self.slug:
            unique_id = get_random_string(length=15)
            self.slug = slugify(self.title) + "-" + unique_id
            self.save()

    class Meta:
        ordering = ['-like_count']
    def __str__(self):
        return self.user.first_name

class Collection(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='collection_detail', null=True, blank=True)
    collection_name = models.CharField(max_length=200, null=True, blank=True)
    collection_description = models.CharField(max_length=250, null=True, blank=True)
    products = models.ManyToManyField(Login_info_table, related_name='collection_products', null=True, blank=True)
    slug = models.SlugField(max_length=255, unique=True, auto_created=True, editable=False)

    def save(self, *args, **kwargs):
        super(Collection, self).save(*args, **kwargs)
        if not self.slug:
            unique_id = get_random_string(length=15)
            self.slug = slugify(self.collection_name) + "-" + unique_id
            self.save()


    def __str__(self):  # __unicode__ on Python 2
        return self.collection_name

art_profile/forms.py
from fileinput import FileInput

from django import forms
from django.forms import PasswordInput, TextInput,FileInput
from django.contrib.auth import authenticate, login

from art_profile.models import Login_info_table

class Art_imageForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(Art_imageForm, self).__init__(*args, **kwargs)
        self.fields['category'].empty_label = 'Select Category'
        self.fields['category'].widget.attrs.update({'onchange': 'categorys(this);'})
        self.fields['title'].widget.attrs.update({'class': 'form-control'})
        self.fields['category'].widget.attrs.update({'class': 'form-control'})

        self.fields['description'].widget.attrs.update({'class': 'form-control'})
        self.fields['image_filename'].widget.attrs.update({'class': 'file-upload-input', 'onchange': 'readURL(this);'})
        self.fields['description'].widget.attrs.update({'class': 'form-control'})


    class Meta:
        model = Login_info_table
        fields = ['category', 'title', 'description', 'title', 'image_filename', 'content_adult_type', 'copyright']
        exclude = ['product_size']

    # def save(self, user, commit=True):
    #     form = super(Art_imageForm, self).save(commit=False)
    #     if commit:
    #         form.user = user
    #         form.save()
    #     return form

class UploaddetailForm(forms.ModelForm):


    class Meta:
        model = Login_info_table
        fields = ['image_filename']

    def save(self, user, commit=True):
        form = super(UploaddetailForm, self).save(commit=False)
        if commit:
            form.user = user
            form.save()
        return form

art_profile/views.py
import json
from datetime import datetime
from django.shortcuts import render
from django.views.generic import FormView, TemplateView, ListView, DetailView
from django.http import HttpResponse
from art_profile.forms import Art_imageForm, UploaddetailForm
from django.core import serializers
from django.template.loader import render_to_string
# Create your views here.
from art_profile.models import Category, SubCategory, Login_info_table
import base64
from django.core.files.base import ContentFile
from django.template.defaultfilters import slugify

class HomeView(TemplateView):
    template_name = 'home.html'

    def get_context_data(self, **kwargs):
        context = super(HomeView, self).get_context_data(**kwargs)
        context['category'] = Category.objects.all()
        return context


class SuccessView(TemplateView):
    form_class = Art_imageForm
    template_name = 'sell.html'

    def dispatch(self, *args, **kwargs):
        return super(SuccessView, self).dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(SuccessView, self).get_context_data(**kwargs)
        context['form'] = self.form_class()
        context['category'] = Category.objects.all()
        return context

    #
    def post(self, request, *args, **kwargs):
        user = request.user
        response_data = {}
        form = self.form_class(request.POST, request.FILES)
        level = request.POST.get('type')
        if level == "level1":
            image_file = request.POST.get('firstimage')
            request.session['image'] = image_file
        elif level == "level2":
            request.session['image'] = request.POST.get('secondimage')
            request.session['content_adult_type'] = False
            if request.POST.get('content_adult_type') == 'on':
                request.session['content_adult_type'] = True

            request.session['copyright'] = False
            if request.POST.get('copyright') == 'on':
                request.session['copyright'] = True

            request.session['title'] = request.POST.get('title')
            request.session['description'] = request.POST.get('description')
            request.session['tags'] = request.POST.getlist('tags')
            request.session['category'] = request.POST.getlist('category')
            request.session['status'] = "Draft"
        if request.POST.get('method_type') == 'get_tags':
            category = request.POST.get('id')
            thepost = Category.objects.get(id=category)
            resultset = thepost.tag_category.all()
            response_data['demo_data'] = render_to_string('ajax/list_tags.html',
                                                          {'tags': resultset})
        if request.POST.get('method_type') == 'save_design':

            data = request.session.get('image')
            if data:
                format, imgstr = data.split(';base64,')
                ext = format.split('/')[-1]
                date_str = datetime.utcnow()
                data = ContentFile(base64.b64decode(imgstr),
                                   name=str('art_image') + date_str.strftime(
                                       "%Y_%m_%d_%H_%M_%S_%f") + '.' + ext)
                category = Category.objects.get(id=request.session.get('category')[0])
                login_table = Login_info_table.objects.create(user=request.user,content_adult_type=request.session.get('content_adult_type'),copyright=request.session.get('copyright'), title=request.session.get('title'),
                                                image_filename=data, description=request.session.get('description'), status="Publish")
                login_table.category = category
                for tag in request.session.get('tags'):
                    try:
                        sub_category = SubCategory.objects.get(id=tag)
                    except:
                        sub_category =SubCategory.objects.create(tag=tag,category=category)
                    login_table.tags.add(sub_category)
                login_table.save()
                request.session['status'] = "Publish"
                del request.session['content_adult_type']
                del request.session['copyright']
                del request.session['title']
                del request.session['image']
                del request.session['category']
                del request.session['tags']
                del request.session['status']



        return HttpResponse(json.dumps(response_data), content_type="application/json")


class PublishView(TemplateView):
    template_name = 'products.html'

    def get_context_data(self, **kwargs):
        context = super(PublishView, self).get_context_data(**kwargs)
        context['category'] = Category.objects.all()
        return context


class AllproductView(ListView):
    model = Login_info_table
    template_name = 'collection.html'

    def get_context_data(self, **kwargs):
        context = super(AllproductView, self).get_context_data(**kwargs)
        # print "Sssssssssss"
        # for table in Login_info_table.objects.all():
        #     table.save()
        #     print  table.slug
        context['category'] = Category.objects.all()
        context['productlist'] = Login_info_table.objects.filter(user=self.request.user)
        return context

    # def update_profile(request, user):
    #     slugs = Login_info_table.objects.get(user=request.user)
    #     slugs.slug = '12341234'
    #     for slug in Login_info_table.objects.all():
    #     user.profile.bio = 'Lorem ipsum dolor sit amet, consectetur adipisicing elit...'
    #     user.save()
    # def create_slug(apps):
    #     Login_info_table = apps.get_model("slug", "Login_info_table")
    #     for slugs in Login_info_table.objects.all():
    #         slugs.slug = slugify(slugs.name)
    #         slugs.save()
    # def create(self):
    #     action = Login_info_table(slug="1234")
    #     action.save()

class SingleproductView(DetailView):
    model = Login_info_table
    form_class = UploaddetailForm
    template_name = 'single-product.html'
    slug_url_kwarg = 'productlist_slug'

    def get_context_data(self, **kwargs):
        context = super(SingleproductView, self).get_context_data(**kwargs)
        context['form'] = self.form_class()
        context['category'] = Category.objects.all()
        context['singleproduct'] = Login_info_table.objects.get(slug=self.kwargs.get('productlist_slug'))
        return context

    def post(self, request, *args, **kwargs):
        user = request.user
        response_data = {}
        id = request.POST.get('valueid')
        print id
        profile = Login_info_table.objects.get(id=id)
        form = self.form_class(request.POST, request.FILES, instance=profile)
        image_filename = request.POST.get('image_filename')
        if form.is_valid():
            form.save(user)
            response_data['status'] = True
        else:
            response_data['status'] = False
            response_data['errors'] = form.errors
            print form.errors.as_text()

        return HttpResponse(json.dumps(response_data), content_type="application/json")

art_profile/templates/collection.html
{% extends 'base.html' %}
{% load static %}
{% block extra_css %}
<link href="{% static 'css/collection-table.css' %}" rel="stylesheet" />
{% endblock %}
{% block content %}



<style>


</style>


    <!-- Sell Starts here-->


    <header class="cd-header">
      <h1>Collection</h1>
    </header>

    <main class="cd-main-content-filter">
      <div class="cd-tab-filter-wrapper">
        <div class="collection-tab">
        </div> <!-- cd-tab-filter -->
      </div> <!-- cd-tab-filter-wrapper -->

      <section class="cd-gallery" style="background-color:#ccc;">

        <div class="col-lg-9 col-md-9 col-sm-3 col-xs-12 prlzero">
          <button class="post-btn ripplelink hvr-shadow">Art Post</button>
          <button class="post-btn ripplelink hvr-shadow">Blog Post</button>

        </div>

        <div id="wrap" class="col-lg-3 col-md-3 col-sm-3 col-xs-12">
          <form action="" autocomplete="on">
          <input id="search" name="search" type="text" placeholder="Search"><input id="search_submit" value="Rechercher" type="submit">
          </form>
        </div>

        <div class="table-responsive-vertical shadow-z-1">
        <!-- Table starts here -->
        <table id="table" class="table table-hover table-mc-light-blue">
            <thead>
              <tr>
                <th class="col-lg-9">Name</th>
                <th class="col-lg-2 t-iems-on-right">Date last updated</th>
                <th class="col-lg-1 t-iems-on-right">More</th>
              </tr>
            </thead>
            <tbody>
            {% for productlist in object_list %}
              <tr>
                <td class="col-lg-9" data-title="Name"><span><img class="collection-list-img" src="{% static productlist.image_filename %}"/></span>{{ productlist.title }}</td>
                <td class="col-lg-2 t-iems-on-right" data-title="Date last updated">
                  <a href="{% url 'art_profile:singleproduct' productlist.slug %}">{{ productlist.status }}</a>
                </td>
                  <td class="col-lg-1 t-iems-on-right" data-title="More"><i class="fa fa-ellipsis-v" aria-hidden="true"></i></td>
              </tr>
            {% endfor %}
            </tbody>
          </table>
        </div>

        <!-- <div class="cd-fail-message">No results found</div> -->
      </section> <!-- cd-gallery -->

      <div class="cd-filter">
        <form>
          <div class="cd-filter-block">
            <h4>MY ART</h4>

            <div class="cd-filter-content">
              <div class="col-lg-12">
                <button class="pub-butn ripplelink hvr-shadow">MANAGE</button>
              </div>
              <div class="col-lg-12 m-tb-20">
                <a href="#"><h5>View storefront</h5></a>
              </div>
            </div> <!-- cd-filter-content -->
          </div> <!-- cd-filter-block -->

          <div class="cd-filter-block">
            <h4>MY ACCOUNT</h4>
            <div class="cd-filter-content">
              <div class="col-lg-12 p-tb-10">
                <p>Earnings</p>
              </div>
              <div class="col-lg-12 p-tb-10">
                <p>Orders</p>
              </div>
              <div class="col-lg-12 p-tb-10">
                <p>Settings</p>
              </div>

            </div> <!-- cd-filter-content -->
          </div> <!-- cd-filter-block -->

          <div class="cd-filter-block">
            <h4>HELP</h4>

            <div class="cd-filter-content">
              <div class="col-lg-12 p-tb-10">
                <p>Changelog</p>
              </div>
              <div class="col-lg-12 p-tb-10">
                <p>Help center</p>
              </div>

            </div> <!-- cd-filter-content -->
          </div> <!-- cd-filter-block -->
        </form>

        <a href="#0" class="cd-close">CLOSE</a>
      </div> <!-- cd-filter -->

      <a href="#0" class="cd-filter-trigger">MANAGE</a>
    </main> <!-- cd-main-content-filter -->

    <div class="cd-filter-footer">

    </div>


    <!-- Sell Ends Here-->



{% endblock %}
{% block extra_js %}
<script src="{% static 'js/collection.js' %}"></script>
<script type="text/javascript">


</script>


<script>
$("#search").keyup(function(){
        _this = this;
        // Show only matching TR, hide rest of them
        $.each($("#table tbody tr"), function() {
            if($(this).text().toLowerCase().indexOf($(_this).val().toLowerCase()) === -1)
               $(this).hide();
            else
               $(this).show();
        });
    });

jQuery(document).ready(function($){
	//open/close lateral filter
	$('.cd-filter-trigger').on('click', function(){
		triggerFilter(true);
	});
	$('.cd-filter .cd-close').on('click', function(){
		triggerFilter(false);
	});

	function triggerFilter($bool) {
		var elementsToTrigger = $([$('.cd-filter-trigger'), $('.cd-filter'), $('.cd-tab-filter'), $('.cd-gallery')]);
		elementsToTrigger.each(function(){
			$(this).toggleClass('filter-is-visible', $bool);
		});
	}

	//mobile version - detect click event on filters tab
	var filter_tab_placeholder = $('.cd-tab-filter .placeholder a'),
		filter_tab_placeholder_default_value = 'Select',
		filter_tab_placeholder_text = filter_tab_placeholder.text();

	$('.cd-tab-filter li').on('click', function(event){
		//detect which tab filter item was selected
		var selected_filter = $(event.target).data('type');

		//check if user has clicked the placeholder item
		if( $(event.target).is(filter_tab_placeholder) ) {
			(filter_tab_placeholder_default_value == filter_tab_placeholder.text()) ? filter_tab_placeholder.text(filter_tab_placeholder_text) : filter_tab_placeholder.text(filter_tab_placeholder_default_value) ;
			$('.cd-tab-filter').toggleClass('is-open');

		//check if user has clicked a filter already selected
		} else if( filter_tab_placeholder.data('type') == selected_filter ) {
			filter_tab_placeholder.text($(event.target).text());
			$('.cd-tab-filter').removeClass('is-open');

		} else {
			//close the dropdown and change placeholder text/data-type value
			$('.cd-tab-filter').removeClass('is-open');
			filter_tab_placeholder.text($(event.target).text()).data('type', selected_filter);
			filter_tab_placeholder_text = $(event.target).text();

			//add class selected to the selected filter item
			$('.cd-tab-filter .selected').removeClass('selected');
			$(event.target).addClass('selected');
		}
	});

	//close filter dropdown inside lateral .cd-filter
	$('.cd-filter-block h4').on('click', function(){
		$(this).toggleClass('closed').siblings('.cd-filter-content').slideToggle(300);
	})

	//fix lateral filter and gallery on scrolling
	$(window).on('scroll', function(){
		(!window.requestAnimationFrame) ? fixGallery() : window.requestAnimationFrame(fixGallery);
	});

	function fixGallery() {
		var offsetTop = $('.cd-main-content-filter').offset().top,
			scrollTop = $(window).scrollTop();
		( scrollTop >= offsetTop ) ? $('.cd-main-content-filter').addClass('is-fixed') : $('.cd-main-content-filter').removeClass('is-fixed');
	}

	/************************************
		MitItUp filter settings
	*************************************/

	buttonFilter.init();
	$('.cd-gallery ul').mixItUp({
	    controls: {
	    	enable: false
	    },
	    callbacks: {
	    	onMixStart: function(){
	    		$('.cd-fail-message').fadeOut(200);
	    	},
	      	onMixFail: function(){
	      		$('.cd-fail-message').fadeIn(200);
	    	}
	    }
	});

	//search filtering
	//credits http://Test Field.io/edprats/pen/pzAdg
	var inputText;
	var $matching = $();

	var delay = (function(){
		var timer = 0;
		return function(callback, ms){
			clearTimeout (timer);
		    timer = setTimeout(callback, ms);
		};
	})();

	$(".cd-filter-content input[type='search']").keyup(function(){
	  	// Delay function invoked to make sure user stopped typing
	  	delay(function(){
	    	inputText = $(".cd-filter-content input[type='search']").val().toLowerCase();
	   		// Check to see if input field is empty
	    	if ((inputText.length) > 0) {
	      		$('.mix').each(function() {
		        	var $this = $(this);

		        	// add item to be filtered out if input text matches items inside the title
		        	if($this.attr('class').toLowerCase().match(inputText)) {
		          		$matching = $matching.add(this);
		        	} else {
		          		// removes any previously matched item
		          		$matching = $matching.not(this);
		        	}
	      		});
	      		$('.cd-gallery ul').mixItUp('filter', $matching);
	    	} else {
	      		// resets the filter to show all item if input is empty
	      		$('.cd-gallery ul').mixItUp('filter', 'all');
	    	}
	  	}, 200 );
	});
});

/*****************************************************
	MixItUp - Define a single object literal
	to contain all filter custom functionality
*****************************************************/
var buttonFilter = {
  	// Declare any variables we will need as properties of the object
  	$filters: null,
  	groups: [],
  	outputArray: [],
  	outputString: '',

  	// The "init" method will run on document ready and cache any jQuery objects we will need.
  	init: function(){
    	var self = this; // As a best practice, in each method we will asign "this" to the variable "self" so that it remains scope-agnostic. We will use it to refer to the parent "buttonFilter" object so that we can share methods and properties between all parts of the object.

    	self.$filters = $('.cd-main-content-filter');
    	self.$container = $('.cd-gallery ul');

	    self.$filters.find('.cd-filters').each(function(){
	      	var $this = $(this);

		    self.groups.push({
		        $inputs: $this.find('.filter'),
		        active: '',
		        tracker: false
		    });
	    });

	    self.bindHandlers();
  	},

  	// The "bindHandlers" method will listen for whenever a button is clicked.
  	bindHandlers: function(){
    	var self = this;

    	self.$filters.on('click', 'a', function(e){
	      	self.parseFilters();
    	});
	    self.$filters.on('change', function(){
	      self.parseFilters();
	    });
  	},

  	parseFilters: function(){
	    var self = this;

	    // loop through each filter group and grap the active filter from each one.
	    for(var i = 0, group; group = self.groups[i]; i++){
	    	group.active = [];
	    	group.$inputs.each(function(){
	    		var $this = $(this);
	    		if($this.is('input[type="radio"]') || $this.is('input[type="checkbox"]')) {
	    			if($this.is(':checked') ) {
	    				group.active.push($this.attr('data-filter'));
	    			}
	    		} else if($this.is('select')){
	    			group.active.push($this.val());
	    		} else if( $this.find('.selected').length > 0 ) {
	    			group.active.push($this.attr('data-filter'));
	    		}
	    	});
	    }
	    self.concatenate();
  	},

  	concatenate: function(){
    	var self = this;

    	self.outputString = ''; // Reset output string

	    for(var i = 0, group; group = self.groups[i]; i++){
	      	self.outputString += group.active;
	    }

	    // If the output string is empty, show all rather than none:
	    !self.outputString.length && (self.outputString = 'all');

    	// Send the output string to MixItUp via the 'filter' method:
		if(self.$container.mixItUp('isLoaded')){
	    	self.$container.mixItUp('filter', self.outputString);
		}
  	}
};
</script>
{% endblock %}
