accounts/urls.py
from django.conf.urls import url
from accounts.views import AdminLoginView, LogoutView

urlpatterns = [
    url(r'^$', AdminLoginView.as_view(), name='adminlogin'),
    url(r'^logout/$', LogoutView.as_view(), name='logout'),

]

printed_vilage/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from art_profile.views import HomeView
from printed_vilage import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^profile/', include('art_profile.urls', namespace='art_profile')),
    url(r'^myprofile/', include('myprofile.urls', namespace='myprofile')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import AbstractUser, UserManager

# Create your models here.
class Login(AbstractUser):
    address = models.CharField(max_length=50,null=True,blank=True)
    mobile = models.IntegerField(default=1)
    image = models.ImageField(upload_to='user')


    objects = UserManager()

    def __str__(self):
        return self.first_name

accounts/forms.py
from django import forms
from django.forms import PasswordInput, TextInput,FileInput
from django.contrib.auth import authenticate, login

from accounts.models import Login

class LoginForm(forms.ModelForm):

    def clean(self):
        email = self.cleaned_data.get('email')
        password = self.cleaned_data.get('password')
        if email and password:
            user = None
            try:
                user = Login.objects.get(email=email,
                                           password=password)
            except:
                raise forms.ValidationError("Please enter a correct email and password.")

            return self.cleaned_data

    class Meta:
        model = Login
        fields = ['email', 'password']

accounts/views.py
from django.shortcuts import render
from django.views.generic import FormView, TemplateView, RedirectView
from django.contrib.auth import authenticate, login, logout
# Create your views here.
from accounts.forms import LoginForm
from accounts.models import Login


# Create your views here.
from art_profile.models import Category


class AdminLoginView(FormView):
    template_name = 'login.html'
    form_class = LoginForm
    success_url = '/'

    def get_context_data(self, **kwargs):
        context = super(AdminLoginView, self).get_context_data(**kwargs)
        context['category'] = Category.objects.all()
        return context

    def form_valid(self, form):
        email = form.cleaned_data.get('email')
        password = form.cleaned_data.get('password')
        user = Login.objects.get(email=email,
                                password=password)
        login(self.request, user)
        return super(AdminLoginView, self).form_valid(form)

    def form_invalid(self, form):
        return super(AdminLoginView, self, ).form_invalid(form)



class LogoutView(RedirectView):
    url = '/'

    def get(self, request, *args, **kwargs):
        if self.request.user.is_authenticated():
            logout(request)
        return super(LogoutView, self).get(request, *args, **kwargs)

accounts/templates/login.html

{% extends 'base.html' %}
{% load static %}
{% block content %}



    <!--&lt;!&ndash;log in start here&ndash;&gt;-->
    <!--<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 account-login">-->
    	<!--<div class="col-md-8 col-md-offset-2">-->
    		<!--<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 login-main">-->
    			  <!--<h1>Login</h1>-->
    		  <!--<div class="col-md-6 login-left">-->
    			<!--<h2>Existing User</h2>-->

    			<!--<form action="{% url 'accounts:adminlogin' %}" method="post">-->
					<!--{% csrf_token %}-->

            <!--<div class="field-container prlzero">-->
              <!--&lt;!&ndash;<input type="text" class="field" placeholder="Username" required="">&ndash;&gt;-->
				<!--{{ form.email }}-->
                <!--{{form.errors.email | striptags }}-->
				<!--{{ form.non_field_errors | striptags }}-->
              <!--<label class="floating-label">Email</label>-->
            <!--</div>-->
            <!--<div class="field-container prlzero">-->
              <!--&lt;!&ndash;<input type="password" class="field" placeholder="Password" required="">&ndash;&gt;-->
				<!--{{ form.password }}-->
            <!--{{form.errors.password}}-->
              <!--<label class="floating-label">Password</label>-->
            <!--</div>-->
    				<!--<input type="submit" class="ripplelink hvr-shadow" value="Login">-->
    			<!--</form>-->

    		  <!--</div>-->
    		  <!--<div class="col-md-6 login-right">-->
    		  	 <!--<h3>New User? Create an Account</h3>-->
    		  	 <!--<p>But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system. and expound the actual teachings of the great.</p>-->
    		     <!--<a href="signup.html" class="login-btn ripplelink hvr-shadow">Create an Account </a>-->
    		  <!--</div>-->
    		  <!--<div class="clearfix"> </div>-->
    		<!--</div>-->
    	<!--</div>-->
    <!--</div>-->
    <!--log in end here-->

    <!--log in start here-->
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 account-login">
    	<div class="col-md-8 col-md-offset-2">
    		<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 login-main">
    			  <h1>Login</h1>
    		  <div class="col-md-6 login-left">
    			<h2>Existing User</h2>

    			<form action="{% url 'accounts:adminlogin' %}" method="post">
					{% csrf_token %}
            <div class="field-container prlzero">
              <input type="text" class="field" placeholder="Email" name="email" id="id_email" required="">
				{{form.errors.email | striptags }}
				{{ form.non_field_errors | striptags }}
              <label class="floating-label">Username</label>
            </div>
            <div class="field-container prlzero">
              <input type="password" class="field" placeholder="Password" name="password" id="id_password" required="">

            {{form.errors.password}}
              <label class="floating-label">Password</label>
            </div>
    				<input type="submit" class="ripplelink" value="Login">
    			</form>

    		  </div>
    		  <div class="col-md-6 login-right">
    		  	 <h3>New User? Create an Account</h3>
    		  	 <p>But I must explain to you how all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of the system. and expound the actual teachings of the great.</p>
    		     <a href="signup.html" class="login-btn ripplelink">Create an Account </a>
    		  </div>
    		  <div class="clearfix"> </div>
    		</div>
    	</div>
    </div>
    <!--log in end here-->

{% endblock %}

